
title: "Sequence Learning"
email: korbinian.riedhammer@fh-rosenheim.de
description: "Materials for Sequence Learning (SL)"

url: "https://sikoried.github.io"
baseurl: "/sequence-learning"

exclude:
  - "LICENSE"
  - "Remarks.md"
  - "jstk"

github_username: ["sikoried"]

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
